version: '3'

dotenv:
  - ".env"
  - ".env.secret"

vars:
  PROVIDER_ID: '{{.PROVIDER_ID | default env "PROVIDER_ID"}}'
  PLUG_DIR:
    sh: "echo $(cd {{.PLUG_DIR}} && pwd)"
  DS_DIR:
    sh: "echo $(cd {{.DS_DIR}} && pwd)"
  DS:
    sh: "echo 'node $(cd {{.DS_DIR}} && pwd)/cli/dist/ds.js'"


includes:
  ds:
    taskfile: ./taskfiles/Taskfile_ds.yml

  fork:
    taskfile: ./taskfiles/Taskfile_fork.yml
    vars:
      FORK_URL: $FORK_URL
      RPC_URL: http://localhost:8545
      FUNDED_ADDRESS: $FORK_FUNDED_ADDRESS
      DEPLOY_PUB: $FORK_DEPLOY_PUB
      DS_ZONE_ADDRESS: $FORK_DS_ZONE_ADDR
      TUGAWAR_ADDRESS: $FORK_TUGAWAR_ADDRESS

  deploy-redstone:
    taskfile: ./taskfiles/Taskfile_deploy_mainnet.yml
    vars:
      DEPLOY_HD_PATH: $REDSTONE_DEPLOY_HD_PATH
      RPC_URL: $REDSTONE_RPC_URL
      DS_ZONE_ADDR: $REDSTONE_DS_ZONE_ADDR

  deploy-garnet:
    taskfile: ./taskfiles/Taskfile_deploy_testnet.yml
    vars:
      RPC_URL: $GARNET_RPC_URL
      FUNDED_ADDRESS: $GARNET_FUNDED_ADDRESS
      FUNDED_KEY: $GARNET_FUNDED_KEY
      DEPLOY_PUB: $GARNET_DEPLOY_PUB
      DS_ZONE_ADDRESS: $GARNET_DS_ZONE_ADDR
      TUGAWAR_ADDRESS: $GARNET_TUGAWAR_ADDRESS

  deploy-sepolia:
    taskfile: ./taskfiles/Taskfile_deploy_testnet.yml
    vars:
      RPC_URL: $OP_SEPOLIA_RPC_URL
      FUNDED_ADDRESS: $OP_SEPOLIA_FUNDED_ADDRESS
      FUNDED_KEY: $OP_SEPOLIA_FUNDED_KEY
      DEPLOY_PUB: $OP_SEPOLIA_DEPLOY_PUB
      DS_ZONE_ADDRESS: $OP_SEPOLIA_DS_ZONE_ADDR
      TUGAWAR_ADDRESS: $OP_SEPOLIA_TUGAWAR_ADDRESS

tasks:
  help:
    dotenv: [".env.{{.PROVIDER_ID}}"]
    desc: extended help and reminders
    cmds:
      - |
        echo "
        PROVIDER_ID: {{.PROVIDER_ID}}
        PROVIDER_ID: $PROVIDER_ID

        PROVIDER_ID: {{.PROVIDER_ID}}
        RPC: $RPC
        Recipies
        
        1. startup local dev for fork testing

           task local-up
           task deploy-contracts

        2. fully deploy ds plugin on local test net

           task local-up
           task deploy-contracts

           # be sure to wait for the ready message in the ds-contracts-1
           # service log

           task ds-apply
        "

  local-down:
    cmds:
      - cd {{.DS_DIR}} && docker compose down

  testnet:deploy-contracts:
    desc:
      deploy the pre-requisite contracts on any testnet
      this task, and all sub tasks are configured to use private keys from env

      AND MAY USE LARGE AMOUNTS OF ETHER

    cmds:
      - task: testnet:deploy-deployment-proxy
      - task: testnet:deploy-6551-reg
      - task: testnet:deploy-account-impl
      - task: testnet:deploy-tugawar
      - task: testnet:deploy-tbas

  fork-tests:
    dotenv: [".env.{{.PROVIDER_ID}}", ".env.{{.PROVIDER_ID}}.6551"]
    desc: |
      run tests. runs forking tests and unit tests

      To run a specific test use '-- --mt testMethod'. arguments after -- are passed
      directly to foundry

    cmds:
      - |
        export ENABLE_FORK_TESTS=true

        [[ -z "$FORK_BLOCK" ]] && FORK_BLOCK=$(cast bn -r $RPC)
        echo "FORK_BLOCK: $FORK_BLOCK"
        export FORK_BLOCK

        export DS_ZONE_ADDR=$(task -s -d {{.ROOT_DIR}} ds-zone-addr)

        FOUNDRY_PROFILE="{{.PROVIDER_ID}}" forge test -vvv {{.CLI_ARGS}}


  check-6551:
    dotenv: [".env.{{.PROVIDER_ID}}"]
    desc: |
      check if the code for the deterministic deployer and the 6551 registry exists

    cmds:
      - |
        echo "$DETERMINISTIC_DEPLOY >"
        cast code \
          -r $RPC \
            $DETERMINISTIC_DEPLOY

        echo "$ERC6551_REGISTRY >"
        cast code \
          -r $RPC \
            $ERC6551_REGISTRY
